In [18]:
library(dplyr)
library(stringr)

#help(package = "dplyr")
#help(package = "stringr")

In [19]:
train <- read.csv("data/titanic/titanic_train.csv", stringsAsFactors = FALSE)
str(train)

head(train, n=10)

'data.frame':	891 obs. of  12 variables:
 $ PassengerId: int  1 2 3 4 5 6 7 8 9 10 ...
 $ Survived   : int  0 1 1 1 0 0 0 0 1 1 ...
 $ Pclass     : int  3 1 3 1 3 3 1 3 3 2 ...
 $ Name       : chr  "Braund, Mr. Owen Harris" "Cumings, Mrs. John Bradley (Florence Briggs Thayer)" "Heikkinen, Miss. Laina" "Futrelle, Mrs. Jacques Heath (Lily May Peel)" ...
 $ Sex        : chr  "male" "female" "female" "female" ...
 $ Age        : num  22 38 26 35 35 NA 54 2 27 14 ...
 $ SibSp      : int  1 1 0 1 0 0 0 3 0 1 ...
 $ Parch      : int  0 0 0 0 0 0 0 1 2 0 ...
 $ Ticket     : chr  "A/5 21171" "PC 17599" "STON/O2. 3101282" "113803" ...
 $ Fare       : num  7.25 71.28 7.92 53.1 8.05 ...
 $ Cabin      : chr  "" "C85" "" "C123" ...
 $ Embarked   : chr  "S" "C" "S" "S" ...

   PassengerId Survived Pclass
1   1          0        3
2   2          1        1
3   3          1        3
4   4          1        1
5   5          0        3
6   6          0        3
7   7          0        1
8   8          0        3
9   9          1        3
10 10          1        2
   Name                                                Sex    Age SibSp Parch
1  Braund, Mr. Owen Harris                             male   22  1     0
2  Cumings, Mrs. John Bradley (Florence Briggs Thayer) female 38  1     0
3  Heikkinen, Miss. Laina                              female 26  0     0
4  Futrelle, Mrs. Jacques Heath (Lily May Peel)        female 35  1     0
5  Allen, Mr. William Henry                            male   35  0     0
6  Moran, Mr. James                                    male   NA  0     0
7  McCarthy, Mr. Timothy J                             male   54  0     0
8  Palsson, Master. Gosta Leonard                      male    2  3     1
9  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   female 27  0     2
10 Nasser, Mrs. Nicholas (Adele Achem)                 female 14  1     0
   Ticket           Fare    Cabin Embarked
1  A/5 21171         7.2500       S
2  PC 17599         71.2833 C85   C
3  STON/O2. 3101282  7.9250       S
4  113803           53.1000 C123  S
5  373450            8.0500       S
6  330877            8.4583       Q
7  17463            51.8625 E46   S
8  349909           21.0750       S
9  347742           11.1333       S
10 237736           30.0708       C

### Fares that Equal Zero
Let's dive deep into fares that are 0

In [20]:
zero.fare <- train %>%  filter(Fare == 0.0)
zero.fare

   PassengerId Survived Pclass Name                             Sex  Age SibSp
1  180         0        3      Leonard, Mr. Lionel              male 36  0
2  264         0        1      Harrison, Mr. William            male 40  0
3  272         1        3      Tornquist, Mr. William Henry     male 25  0
4  278         0        2      Parkes, Mr. Francis "Frank"      male NA  0
5  303         0        3      Johnson, Mr. William Cahoone Jr  male 19  0
6  414         0        2      Cunningham, Mr. Alfred Fleming   male NA  0
7  467         0        2      Campbell, Mr. William            male NA  0
8  482         0        2      Frost, Mr. Anthony Wood "Archie" male NA  0
9  598         0        3      Johnson, Mr. Alfred              male 49  0
10 634         0        1      Parr, Mr. William Henry Marsh    male NA  0
11 675         0        2      Watson, Mr. Ennis Hastings       male NA  0
12 733         0        2      Knight, Mr. Robert J             male NA  0
13 807         0        1      Andrews, Mr. Thomas Jr           male 39  0
14 816         0        1      Fry, Mr. Richard                 male NA  0
15 823         0        1      Reuchlin, Jonkheer. John George  male 38  0
   Parch Ticket Fare Cabin Embarked
1  0     LINE   0          S
2  0     112059 0    B94   S
3  0     LINE   0          S
4  0     239853 0          S
5  0     LINE   0          S
6  0     239853 0          S
7  0     239853 0          S
8  0     239854 0          S
9  0     LINE   0          S
10 0     112052 0          S
11 0     239856 0          S
12 0     239855 0          S
13 0     112050 0    A36   S
14 0     112058 0    B102  S
15 0     19972  0          S

In [21]:
# Let's get the totals by Pclass
zero.fare.pclass <- zero.fare %>% group_by(Pclass) %>% summarize(Total = n()) %>% arrange(desc(Total))
zero.fare.pclass

  Pclass Total
1 2      6
2 1      5
3 3      4

In [22]:
train <- train %>% mutate(Title = str_extract(Name, "[a-zA-Z]+\\."))
train

    PassengerId Survived Pclass
1    1          0        3
2    2          1        1
3    3          1        3
4    4          1        1
5    5          0        3
6    6          0        3
7    7          0        1
8    8          0        3
9    9          1        3
10  10          1        2
11  11          1        3
12  12          1        1
13  13          0        3
14  14          0        3
15  15          0        3
16  16          1        2
17  17          0        3
18  18          1        2
19  19          0        3
20  20          1        3
21  21          0        2
22  22          1        2
23  23          1        3
24  24          1        1
25  25          0        3
26  26          1        3
27  27          0        3
28  28          0        1
29  29          1        3
30  30          0        3
... ...         ...      ...
862 862         0        2
863 863         1        1
864 864         0        3
865 865         0        2
866 866         1        2
867 867         1        2
868 868         0        1
869 869         0        3
870 870         1        3
871 871         0        3
872 872         1        1
873 873         0        1
874 874         0        3
875 875         1        2
876 876         1        3
877 877         0        3
878 878         0        3
879 879         0        3
880 880         1        1
881 881         1        2
882 882         0        3
883 883         0        3
884 884         0        2
885 885         0        3
886 886         0        3
887 887         0        2
888 888         1        1
889 889         0        3
890 890         1        1
891 891         0        3
    Name                                                      Sex    Age SibSp
1   Braund, Mr. Owen Harris                                   male   22  1
2   Cumings, Mrs. John Bradley (Florence Briggs Thayer)       female 38  1
3   Heikkinen, Miss. Laina                                    female 26  0
4   Futrelle, Mrs. Jacques Heath (Lily May Peel)              female 35  1
5   Allen, Mr. William Henry                                  male   35  0
6   Moran, Mr. James                                          male   NA  0
7   McCarthy, Mr. Timothy J                                   male   54  0
8   Palsson, Master. Gosta Leonard                            male    2  3
9   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         female 27  0
10  Nasser, Mrs. Nicholas (Adele Achem)                       female 14  1
11  Sandstrom, Miss. Marguerite Rut                           female  4  1
12  Bonnell, Miss. Elizabeth                                  female 58  0
13  Saundercock, Mr. William Henry                            male   20  0
14  Andersson, Mr. Anders Johan                               male   39  1
15  Vestrom, Miss. Hulda Amanda Adolfina                      female 14  0
16  Hewlett, Mrs. (Mary D Kingcome)                           female 55  0
17  Rice, Master. Eugene                                      male    2  4
18  Williams, Mr. Charles Eugene                              male   NA  0
19  Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)   female 31  1
20  Masselmani, Mrs. Fatima                                   female NA  0
21  Fynney, Mr. Joseph J                                      male   35  0
22  Beesley, Mr. Lawrence                                     male   34  0
23  McGowan, Miss. Anna "Annie"                               female 15  0
24  Sloper, Mr. William Thompson                              male   28  0
25  Palsson, Miss. Torborg Danira                             female  8  3
26  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson) female 38  1
27  Emir, Mr. Farred Chehab                                   male   NA  0
28  Fortune, Mr. Charles Alexander                            male   19  3
29  O'Dwyer, Miss. Ellen "Nellie"                             female NA  0
30  Todoroff, Mr. Lalio                                       male   NA  0
... ...                                                       ...    ... ...
862 Giles, Mr. Frederick Edward                               male   21  1
863 Swift, Mrs. Frederick Joel (Margaret Welles Barron)       female 48  0
864 Sage, Miss. Dorothy Edith "Dolly"                         female NA  8
865 Gill, Mr. John William                                    male   24  0
866 Bystrom, Mrs. (Karolina)                                  female 42  0
867 Duran y More, Miss. Asuncion                              female 27  1
868 Roebling, Mr. Washington Augustus II                      male   31  0
869 van Melkebeke, Mr. Philemon                               male   NA  0
870 Johnson, Master. Harold Theodor                           male    4  1
871 Balkic, Mr. Cerin                                         male   26  0
872 Beckwith, Mrs. Richard Leonard (Sallie Monypeny)          female 47  1
873 Carlsson, Mr. Frans Olof                                  male   33  0
874 Vander Cruyssen, Mr. Victor                               male   47  0
875 Abelson, Mrs. Samuel (Hannah Wizosky)                     female 28  1
876 Najib, Miss. Adele Kiamie "Jane"                          female 15  0
877 Gustafsson, Mr. Alfred Ossian                             male   20  0
878 Petroff, Mr. Nedelio                                      male   19  0
879 Laleff, Mr. Kristo                                        male   NA  0
880 Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)             female 56  0
881 Shelley, Mrs. William (Imanita Parrish Hall)              female 25  0
882 Markun, Mr. Johann                                        male   33  0
883 Dahlberg, Miss. Gerda Ulrika                              female 22  0
884 Banfield, Mr. Frederick James                             male   28  0
885 Sutehall, Mr. Henry Jr                                    male   25  0
886 Rice, Mrs. William (Margaret Norton)                      female 39  0
887 Montvila, Rev. Juozas                                     male   27  0
888 Graham, Miss. Margaret Edith                              female 19  0
889 Johnston, Miss. Catherine Helen "Carrie"                  female NA  1
890 Behr, Mr. Karl Howell                                     male   26  0
891 Dooley, Mr. Patrick                                       male   32  0
    Parch Ticket           Fare     Cabin       Embarked Title
1   0     A/5 21171          7.2500             S        Mr.
2   0     PC 17599          71.2833 C85         C        Mrs.
3   0     STON/O2. 3101282   7.9250             S        Miss.
4   0     113803            53.1000 C123        S        Mrs.
5   0     373450             8.0500             S        Mr.
6   0     330877             8.4583             Q        Mr.
7   0     17463             51.8625 E46         S        Mr.
8   1     349909            21.0750             S        Master.
9   2     347742            11.1333             S        Mrs.
10  0     237736            30.0708             C        Mrs.
11  1     PP 9549           16.7000 G6          S        Miss.
12  0     113783            26.5500 C103        S        Miss.
13  0     A/5. 2151          8.0500             S        Mr.
14  5     347082            31.2750             S        Mr.
15  0     350406             7.8542             S        Miss.
16  0     248706            16.0000             S        Mrs.
17  1     382652            29.1250             Q        Master.
18  0     244373            13.0000             S        Mr.
19  0     345763            18.0000             S        Mrs.
20  0     2649               7.2250             C        Mrs.
21  0     239865            26.0000             S        Mr.
22  0     248698            13.0000 D56         S        Mr.
23  0     330923             8.0292             Q        Miss.
24  0     113788            35.5000 A6          S        Mr.
25  1     349909            21.0750             S        Miss.
26  5     347077            31.3875             S        Mrs.
27  0     2631               7.2250             C        Mr.
28  2     19950            263.0000 C23 C25 C27 S        Mr.
29  0     330959             7.8792             Q        Miss.
30  0     349216             7.8958             S        Mr.
... ...   ...              ...      ...         ...      ...
862 0     28134            11.5000              S        Mr.
863 0     17466            25.9292  D17         S        Mrs.
864 2     CA. 2343         69.5500              S        Miss.
865 0     233866           13.0000              S        Mr.
866 0     236852           13.0000              S        Mrs.
867 0     SC/PARIS 2149    13.8583              C        Miss.
868 0     PC 17590         50.4958  A24         S        Mr.
869 0     345777            9.5000              S        Mr.
870 1     347742           11.1333              S        Master.
871 0     349248            7.8958              S        Mr.
872 1     11751            52.5542  D35         S        Mrs.
873 0     695               5.0000  B51 B53 B55 S        Mr.
874 0     345765            9.0000              S        Mr.
875 0     P/PP 3381        24.0000              C        Mrs.
876 0     2667              7.2250              C        Miss.
877 0     7534              9.8458              S        Mr.
878 0     349212            7.8958              S        Mr.
879 0     349217            7.8958              S        Mr.
880 1     11767            83.1583  C50         C        Mrs.
881 1     230433           26.0000              S        Mrs.
882 0     349257            7.8958              S        Mr.
883 0     7552             10.5167              S        Miss.
884 0     C.A./SOTON 34068 10.5000              S        Mr.
885 0     SOTON/OQ 392076   7.0500              S        Mr.
886 5     382652           29.1250              Q        Mrs.
887 0     211536           13.0000              S        Rev.
888 0     112053           30.0000  B42         S        Miss.
889 2     W./C. 6607       23.4500              S        Miss.
890 0     111369           30.0000  C148        C        Mr.
891 0     370376            7.7500              Q        Mr.

In [23]:
titles.lookup <- data.frame(Title = c("Mr.", "Capt.", "Col.", "Don.", "Dr.",
                                      "Jonkheer.", "Major.", "Rev.", "Sir.",
                                      "Mrs.", "Dona.", "Lady.", "Mme.", 
                                      "Countess.", 
                                      "Miss.", "Mlle.", "Ms.",
                                      "Master."),
                            New.Title = c(rep("Mr.", 9),
                                          rep("Mrs.", 5),
                                          rep("Miss.", 3),
                                          "Master."),
                            stringsAsFactors = FALSE)
titles.lookup

   Title     New.Title
1  Mr.       Mr.
2  Capt.     Mr.
3  Col.      Mr.
4  Don.      Mr.
5  Dr.       Mr.
6  Jonkheer. Mr.
7  Major.    Mr.
8  Rev.      Mr.
9  Sir.      Mr.
10 Mrs.      Mrs.
11 Dona.     Mrs.
12 Lady.     Mrs.
13 Mme.      Mrs.
14 Countess. Mrs.
15 Miss.     Miss.
16 Mlle.     Miss.
17 Ms.       Miss.
18 Master.   Master.

In [24]:
# Replace Titles using lookup table
train <- train %>% left_join(titles.lookup, by = "Title")
train

    PassengerId Survived Pclass
1    1          0        3
2    2          1        1
3    3          1        3
4    4          1        1
5    5          0        3
6    6          0        3
7    7          0        1
8    8          0        3
9    9          1        3
10  10          1        2
11  11          1        3
12  12          1        1
13  13          0        3
14  14          0        3
15  15          0        3
16  16          1        2
17  17          0        3
18  18          1        2
19  19          0        3
20  20          1        3
21  21          0        2
22  22          1        2
23  23          1        3
24  24          1        1
25  25          0        3
26  26          1        3
27  27          0        3
28  28          0        1
29  29          1        3
30  30          0        3
... ...         ...      ...
862 862         0        2
863 863         1        1
864 864         0        3
865 865         0        2
866 866         1        2
867 867         1        2
868 868         0        1
869 869         0        3
870 870         1        3
871 871         0        3
872 872         1        1
873 873         0        1
874 874         0        3
875 875         1        2
876 876         1        3
877 877         0        3
878 878         0        3
879 879         0        3
880 880         1        1
881 881         1        2
882 882         0        3
883 883         0        3
884 884         0        2
885 885         0        3
886 886         0        3
887 887         0        2
888 888         1        1
889 889         0        3
890 890         1        1
891 891         0        3
    Name                                                      Sex    Age SibSp
1   Braund, Mr. Owen Harris                                   male   22  1
2   Cumings, Mrs. John Bradley (Florence Briggs Thayer)       female 38  1
3   Heikkinen, Miss. Laina                                    female 26  0
4   Futrelle, Mrs. Jacques Heath (Lily May Peel)              female 35  1
5   Allen, Mr. William Henry                                  male   35  0
6   Moran, Mr. James                                          male   NA  0
7   McCarthy, Mr. Timothy J                                   male   54  0
8   Palsson, Master. Gosta Leonard                            male    2  3
9   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)         female 27  0
10  Nasser, Mrs. Nicholas (Adele Achem)                       female 14  1
11  Sandstrom, Miss. Marguerite Rut                           female  4  1
12  Bonnell, Miss. Elizabeth                                  female 58  0
13  Saundercock, Mr. William Henry                            male   20  0
14  Andersson, Mr. Anders Johan                               male   39  1
15  Vestrom, Miss. Hulda Amanda Adolfina                      female 14  0
16  Hewlett, Mrs. (Mary D Kingcome)                           female 55  0
17  Rice, Master. Eugene                                      male    2  4
18  Williams, Mr. Charles Eugene                              male   NA  0
19  Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)   female 31  1
20  Masselmani, Mrs. Fatima                                   female NA  0
21  Fynney, Mr. Joseph J                                      male   35  0
22  Beesley, Mr. Lawrence                                     male   34  0
23  McGowan, Miss. Anna "Annie"                               female 15  0
24  Sloper, Mr. William Thompson                              male   28  0
25  Palsson, Miss. Torborg Danira                             female  8  3
26  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson) female 38  1
27  Emir, Mr. Farred Chehab                                   male   NA  0
28  Fortune, Mr. Charles Alexander                            male   19  3
29  O'Dwyer, Miss. Ellen "Nellie"                             female NA  0
30  Todoroff, Mr. Lalio                                       male   NA  0
... ...                                                       ...    ... ...
862 Giles, Mr. Frederick Edward                               male   21  1
863 Swift, Mrs. Frederick Joel (Margaret Welles Barron)       female 48  0
864 Sage, Miss. Dorothy Edith "Dolly"                         female NA  8
865 Gill, Mr. John William                                    male   24  0
866 Bystrom, Mrs. (Karolina)                                  female 42  0
867 Duran y More, Miss. Asuncion                              female 27  1
868 Roebling, Mr. Washington Augustus II                      male   31  0
869 van Melkebeke, Mr. Philemon                               male   NA  0
870 Johnson, Master. Harold Theodor                           male    4  1
871 Balkic, Mr. Cerin                                         male   26  0
872 Beckwith, Mrs. Richard Leonard (Sallie Monypeny)          female 47  1
873 Carlsson, Mr. Frans Olof                                  male   33  0
874 Vander Cruyssen, Mr. Victor                               male   47  0
875 Abelson, Mrs. Samuel (Hannah Wizosky)                     female 28  1
876 Najib, Miss. Adele Kiamie "Jane"                          female 15  0
877 Gustafsson, Mr. Alfred Ossian                             male   20  0
878 Petroff, Mr. Nedelio                                      male   19  0
879 Laleff, Mr. Kristo                                        male   NA  0
880 Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)             female 56  0
881 Shelley, Mrs. William (Imanita Parrish Hall)              female 25  0
882 Markun, Mr. Johann                                        male   33  0
883 Dahlberg, Miss. Gerda Ulrika                              female 22  0
884 Banfield, Mr. Frederick James                             male   28  0
885 Sutehall, Mr. Henry Jr                                    male   25  0
886 Rice, Mrs. William (Margaret Norton)                      female 39  0
887 Montvila, Rev. Juozas                                     male   27  0
888 Graham, Miss. Margaret Edith                              female 19  0
889 Johnston, Miss. Catherine Helen "Carrie"                  female NA  1
890 Behr, Mr. Karl Howell                                     male   26  0
891 Dooley, Mr. Patrick                                       male   32  0
    Parch Ticket           Fare     Cabin       Embarked Title   New.Title
1   0     A/5 21171          7.2500             S        Mr.     Mr.
2   0     PC 17599          71.2833 C85         C        Mrs.    Mrs.
3   0     STON/O2. 3101282   7.9250             S        Miss.   Miss.
4   0     113803            53.1000 C123        S        Mrs.    Mrs.
5   0     373450             8.0500             S        Mr.     Mr.
6   0     330877             8.4583             Q        Mr.     Mr.
7   0     17463             51.8625 E46         S        Mr.     Mr.
8   1     349909            21.0750             S        Master. Master.
9   2     347742            11.1333             S        Mrs.    Mrs.
10  0     237736            30.0708             C        Mrs.    Mrs.
11  1     PP 9549           16.7000 G6          S        Miss.   Miss.
12  0     113783            26.5500 C103        S        Miss.   Miss.
13  0     A/5. 2151          8.0500             S        Mr.     Mr.
14  5     347082            31.2750             S        Mr.     Mr.
15  0     350406             7.8542             S        Miss.   Miss.
16  0     248706            16.0000             S        Mrs.    Mrs.
17  1     382652            29.1250             Q        Master. Master.
18  0     244373            13.0000             S        Mr.     Mr.
19  0     345763            18.0000             S        Mrs.    Mrs.
20  0     2649               7.2250             C        Mrs.    Mrs.
21  0     239865            26.0000             S        Mr.     Mr.
22  0     248698            13.0000 D56         S        Mr.     Mr.
23  0     330923             8.0292             Q        Miss.   Miss.
24  0     113788            35.5000 A6          S        Mr.     Mr.
25  1     349909            21.0750             S        Miss.   Miss.
26  5     347077            31.3875             S        Mrs.    Mrs.
27  0     2631               7.2250             C        Mr.     Mr.
28  2     19950            263.0000 C23 C25 C27 S        Mr.     Mr.
29  0     330959             7.8792             Q        Miss.   Miss.
30  0     349216             7.8958             S        Mr.     Mr.
... ...   ...              ...      ...         ...      ...     ...
862 0     28134            11.5000              S        Mr.     Mr.
863 0     17466            25.9292  D17         S        Mrs.    Mrs.
864 2     CA. 2343         69.5500              S        Miss.   Miss.
865 0     233866           13.0000              S        Mr.     Mr.
866 0     236852           13.0000              S        Mrs.    Mrs.
867 0     SC/PARIS 2149    13.8583              C        Miss.   Miss.
868 0     PC 17590         50.4958  A24         S        Mr.     Mr.
869 0     345777            9.5000              S        Mr.     Mr.
870 1     347742           11.1333              S        Master. Master.
871 0     349248            7.8958              S        Mr.     Mr.
872 1     11751            52.5542  D35         S        Mrs.    Mrs.
873 0     695               5.0000  B51 B53 B55 S        Mr.     Mr.
874 0     345765            9.0000              S        Mr.     Mr.
875 0     P/PP 3381        24.0000              C        Mrs.    Mrs.
876 0     2667              7.2250              C        Miss.   Miss.
877 0     7534              9.8458              S        Mr.     Mr.
878 0     349212            7.8958              S        Mr.     Mr.
879 0     349217            7.8958              S        Mr.     Mr.
880 1     11767            83.1583  C50         C        Mrs.    Mrs.
881 1     230433           26.0000              S        Mrs.    Mrs.
882 0     349257            7.8958              S        Mr.     Mr.
883 0     7552             10.5167              S        Miss.   Miss.
884 0     C.A./SOTON 34068 10.5000              S        Mr.     Mr.
885 0     SOTON/OQ 392076   7.0500              S        Mr.     Mr.
886 5     382652           29.1250              Q        Mrs.    Mrs.
887 0     211536           13.0000              S        Rev.    Mr.
888 0     112053           30.0000  B42         S        Miss.   Miss.
889 2     W./C. 6607       23.4500              S        Miss.   Miss.
890 0     111369           30.0000  C148        C        Mr.     Mr.
891 0     370376            7.7500              Q        Mr.     Mr.